server:
  port: 80
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:mysql://192.168.0.20:3306/ems?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name : com.mysql.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
mybatis:
  config-location: classpath:mybatis-config.xml
  type-aliases-package: com.tdmh.entity
  mapper-locations: classpath:mappers/*Mapper.xml
