spring:
  datasource:
    url: jdbc:mysql://local:3306/ems?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name : com.mysql.jdbc.Driver