server:
  port: 80
  servlet:
    context-path: /
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  profiles:
    active: @active_profile@
mybatis:
  config-location: classpath:mybatis-config.xml
  type-aliases-package: com.tdmh.entity
  mapper-locations: classpath:mappers/*Mapper.xml
logging:
  config: classpath:logback.xml


