spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ems?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8
    username: root
    password: sm2017
    driver-class-name : com.mysql.jdbc.Driver
lyims:
  serverIp: 192.168.0.142
  serverPort: 8080