spring:
  datasource:
    url: jdbc:mysql://192.168.0.20:3306/ems?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name : com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.tdmh.entity
  config-location: classpath:mybatis-config.xml
