spring:
  datasource:
    url : jdbc:mysql://localhost:3306/ems
    username : root
    password : 123456
    driver-class-name : com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.tdmh.entity
